<html>
    <head>
        <link href="/public/css/bootstrap.min.css" rel="stylesheet" type="text/css">
        <script type="text/javascript" src="/public/js/bootstrap.min.js"></script>
    </head>
    <body>
	    <nav class="navbar  ">
		    <ul class="nav nav-tabs navbar-inverse">
  <li role="presentation" class="active"><a href="#">Home</a></li>
  <li role="presentation"><a href="#">Profile</a></li>
  <li role="presentation"><a href="#">Messages</a></li>
</ul>
	    </nav>
	    <div class="container">
		    <div class="page-header">
  <h1>Example page header <small>Subtext for header</small></h1>
</div>
		    <p class="lead">
			    <?php
echo $content, " I am ", $name;
?>
		    </p>
	    </div>
    </body>
</html>

