<html>
    <head>
        <?php include(APPLICATION_APP_VIEW_PATH . "/base/header.phtml"); ?>
    </head>
    <body>
	    <?php include(APPLICATION_APP_VIEW_PATH . "/base/nav.phtml"); ?>
	    <div class="container">
		    <div class="page-header">
  <h1>Example page header <small>Subtext for header</small></h1>
</div>
		    <p class="lead">
			    <?php
echo $content, " I am ", $name;
?>
		    </p>
	    </div>
	    <?php include(APPLICATION_APP_VIEW_PATH . "/base/footer.phtml"); ?>
    </body>
</html>

